export const contactAssetManifest = [
  {
    name: 'Contact Hero Collaboration Gateway',
    purpose: 'Hero right-side collaboration gateway visual.',
    visualRole: 'Dual collaboration nodes converging into a central connection point.',
    renderType: 'img',
    containsText: false,
    responsiveRule: 'Keep aspect ratio with object-fit: contain; position below copy on mobile.',
    fileName: 'contact-hero-collaboration-gateway.png',
    width: 1150,
    height: 380,
    source: 'contact-design-clean.png.png',
  },
  {
    name: 'Product Leadership Collaboration Area',
    purpose: 'Product Leadership collaboration direction visual.',
    visualRole: 'People collaboration icon with orbital gold light.',
    renderType: 'img',
    containsText: false,
    responsiveRule: 'Keep with its corresponding content block; stack above or beside copy on mobile.',
    fileName: 'contact-area-product-leadership.png',
    width: 235,
    height: 195,
    source: 'contact-design-clean.png.png',
  },
  {
    name: 'AI Product Innovation Collaboration Area',
    purpose: 'AI Product Innovation collaboration direction visual.',
    visualRole: 'Product cube with orbital gold light.',
    renderType: 'img',
    containsText: false,
    responsiveRule: 'Keep with its corresponding content block; stack above or beside copy on mobile.',
    fileName: 'contact-area-ai-product-innovation.png',
    width: 245,
    height: 195,
    source: 'contact-design-clean.png.png',
  },
  {
    name: 'Digital Transformation Collaboration Area',
    purpose: 'Digital Transformation collaboration direction visual.',
    visualRole: 'Growth icon with orbital gold light.',
    renderType: 'img',
    containsText: false,
    responsiveRule: 'Keep with its corresponding content block; stack above or beside copy on mobile.',
    fileName: 'contact-area-digital-transformation.png',
    width: 250,
    height: 195,
    source: 'contact-design-clean.png.png',
  },
  {
    name: 'Email Channel Icon',
    purpose: 'Email contact channel icon.',
    visualRole: 'Gold envelope icon and ambient glow.',
    renderType: 'img',
    containsText: false,
    responsiveRule: 'Maintain intrinsic ratio; remain adjacent to the Email text on all breakpoints.',
    fileName: 'contact-channel-email-icon.png',
    width: 120,
    height: 125,
    source: 'contact-design-clean.png.png',
  },
  {
    name: 'Executive Profile Channel Icon',
    purpose: 'Executive Profile contact channel icon.',
    visualRole: 'Gold document icon and ambient glow.',
    renderType: 'img',
    containsText: false,
    responsiveRule: 'Maintain intrinsic ratio; remain adjacent to the profile text on all breakpoints.',
    fileName: 'contact-channel-executive-profile-icon.png',
    width: 125,
    height: 125,
    source: 'contact-design-clean.png.png',
  },
  {
    name: 'LinkedIn Channel Icon',
    purpose: 'LinkedIn contact channel icon.',
    visualRole: 'Gold LinkedIn icon and ambient glow.',
    renderType: 'img',
    containsText: false,
    responsiveRule: 'Maintain intrinsic ratio; remain adjacent to the LinkedIn text on all breakpoints.',
    fileName: 'contact-channel-linkedin-icon.png',
    width: 125,
    height: 125,
    source: 'contact-design-clean.png.png',
  },
  {
    name: 'Contact Closing Background',
    purpose: 'Contact closing philosophy background.',
    visualRole: 'Black-gold horizon, central light source, and connection-network texture.',
    renderType: 'background-image',
    containsText: false,
    responsiveRule: 'Anchor center bottom; keep the text layer independent and allow the section to grow naturally.',
    fileName: 'contact-closing-background.png',
    width: 1536,
    height: 219,
    source: 'contact-design-clean.png.png',
  },
] as const
